# docker-compose.yml

version: '3.12'

services:
  app:
    image : genai-image
    container_name: genai-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - ./data:/app/core/docs  # Volume for storing files in core/docs
      - ./logs:/app/logs  # Volume for storing logs
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
